<a href="https://colab.research.google.com/github/Tahsin-20/Python-Libraries/blob/main/Numpy_Basics-01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [109]:
import numpy as np

# **Basic operations**



In [110]:
a=np.array([1, 2, 3])
print(a)

[1 2 3]


In [111]:
b=np.array([[2.0, 3.0, 5.9],[4.9, 6.7, 3.4]])
print(b)

[[2.  3.  5.9]
 [4.9 6.7 3.4]]


In [112]:
#Get dimension
a.ndim
b.ndim

2

In [113]:
#Get shape
a.shape
b.shape

(2, 3)

In [114]:
#Get data type
a.dtype
b.dtype

dtype('float64')

In [115]:
#Get size
a.itemsize
b.itemsize

8

In [116]:
#Get total size
a.nbytes
b.nbytes

48

# **Accessing/Changing Specific elements, rows, columns etc**

In [117]:
a=np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])

In [118]:
#Get a specific element [r, c]
a[1,0]
a[1, -7]

np.int64(8)

In [119]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [120]:
#Get a specific column
a[:, 3]

array([ 4, 11])

In [121]:
#Fancy way [row/col.no, start_index : stop_index : step_size]
a[0, 1:6:2]

array([2, 4, 6])

In [122]:
#Changing elements
a[1,3]=20
#Changing series of elements
a[:,3]=30
print(a)

[[ 1  2  3 30  5  6  7]
 [ 8  9 10 30 12 13 14]]


**3D Example**

In [123]:
b=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [124]:
#Get specific element (work outside in)
b[0,1,1]
b[0, :, 1]

array([2, 4])

In [125]:
#Replace
b[: , 1, :]=[[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# **Initializing different types of array**

In [126]:
#All 0s matrix
np.zeros(5)
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [127]:
#All 1s matrix
np.ones(4)
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [128]:
#All any number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [129]:
#All any number in an already created array (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [130]:
#Random decimal numbers
np.random.rand(5,6)

array([[0.07916613, 0.88077974, 0.73226614, 0.01599914, 0.28816062,
        0.29385361],
       [0.34256734, 0.51222463, 0.97762101, 0.60982306, 0.92494992,
        0.76902551],
       [0.03760899, 0.83069059, 0.22310378, 0.29872825, 0.0476897 ,
        0.06734704],
       [0.08116568, 0.35178013, 0.79355933, 0.26747431, 0.62790358,
        0.7265502 ],
       [0.59653373, 0.9562827 , 0.89112959, 0.8322065 , 0.40502754,
        0.63612355]])

In [131]:
#Random integer number (from, to[exclusive], size=(r, c))
np.random.randint(2,6, size=(3,3))

array([[4, 4, 2],
       [2, 2, 5],
       [2, 5, 3]])

In [132]:
#Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [133]:
#Repeat an array
arr=np.array([[1, 2, 3]])
r1=np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [134]:
#Copying arrays
d=np.array([1, 2, 3])
c=d.copy()
c[0]=100
print(c)
print(d)

[100   2   3]
[1 2 3]


# **Mathematical Operations**

In [135]:
#Addition
a=np.array([1, 2, 3, 4])
a+2

array([3, 4, 5, 6])

In [136]:
#Subtraction
a=np.array([1, 2, 3, 4])
a-2

array([-1,  0,  1,  2])

In [137]:
#Multiplication
a=np.array([1, 2, 3, 4])
a*2

array([2, 4, 6, 8])

In [138]:
#Division
a=np.array([1, 2, 3, 4])
a/2

array([0.5, 1. , 1.5, 2. ])

In [139]:
#Power
a=np.array([1, 2, 3, 4])
a**2

array([ 1,  4,  9, 16])

In [140]:
#Take sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [141]:
#Take cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [142]:
#You can do all the things between two numpy arrays too
a=np.array([1, 2, 3, 4])
b=np.array([1, 0, 1, 0])
a+b
a-b
a*b
a/b #smth / 0 is infinity

/tmp/ipykernel_15238/3311733407.py:7: RuntimeWarning: divide by zero encountered in divide
  a/b #smth / 0 is infinity


array([ 1., inf,  3., inf])

# **Linear Algebra**

In [143]:
#Multiplication of two matrices
e=np.ones((2,3))
print(e)
f=np.full((3,2),2)
print(f)

np.matmul(e,f)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [144]:
A = np.array([[4, 11, 14],
              [8, 7, -2],
              [1, 5, 3]])

In [145]:
#Find the determinant
np.linalg.det(A)

np.float64(299.99999999999994)

In [146]:
#Trace of matrix
np.trace(A)

np.int64(14)

In [147]:
#Singular vector decomposition
np.linalg.svd(A)

SVDResult(U=array([[-0.90749124,  0.32823268, -0.26215065],
       [-0.3056737 , -0.9440455 , -0.12386152],
       [-0.28813755, -0.03227069,  0.95704512]]), S=array([19.80787839,  9.49221315,  1.59556982]), Vh=array([[-0.32126066, -0.68471782, -0.65418124],
       [-0.66072094, -0.33281095,  0.67281848],
       [-0.67840948,  0.64838136, -0.34548833]]))

In [148]:
#Eigenvalues & Eigenvectors
np.linalg.eig(A)

EigResult(eigenvalues=array([16.88759423+0.j        , -1.44379712+3.95979413j,
       -1.44379712-3.95979413j]), eigenvectors=array([[ 0.77541218+0.j        ,  0.71673995+0.j        ,
         0.71673995-0.j        ],
       [ 0.57426679+0.j        , -0.55709462-0.17977938j,
        -0.55709462+0.17977938j],
       [ 0.2625902 +0.j        ,  0.15901814+0.3439797j ,
         0.15901814-0.3439797j ]]))

In [149]:
#Matrix norms
np.linalg.norm(A) #Standard Frobenius norm
np.linalg.norm(A, ord=2) #Spectral norm (L2 norm)

np.float64(19.807878393893564)

In [150]:
#Inverse of matrix
np.linalg.inv(A)

array([[ 0.10333333,  0.12333333, -0.4       ],
       [-0.08666667, -0.00666667,  0.4       ],
       [ 0.11      , -0.03      , -0.2       ]])

# **Statistics**

In [151]:
stats=np.array([[1, 2, 3], [4, 5, 6]])

In [152]:
#Minimum number
np.min(stats)
np.min(stats, axis=0)
np.min(stats, axis=1)

array([1, 4])

In [153]:
#Maximum number
np.max(stats)
np.max(stats, axis=0)
np.max(stats, axis=1)

array([3, 6])

In [154]:
#Summation
np.sum(stats)
np.sum(stats, axis=0)
np.sum(stats, axis=1)

array([ 6, 15])

# **Reorganizing arrays**

In [155]:
#Reshaping matrices (Be careful with invalid reshaping)
before=np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after=before.reshape((8,1))
after=before.reshape((4,2))
after=before.reshape((2,2,2))
after=before.reshape((2,4))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [156]:
#Vertically stacking vectors
v1=np.array([1, 2, 3, 4])
v2=np.array([5, 6, 7, 8])

np.vstack([v1, v2])
np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [157]:
#Horizontal stacking vectors
h1=np.ones((2,4))
h2=np.zeros((2,2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# **Miscellaneous**

In [158]:
%%writefile data.txt
13, 14, 17, 18, 19
4, 5, 8, 3, 20
34, 50, 100, 60, 70

Overwriting data.txt


In [159]:
#Load data from a file
filedata=np.genfromtxt('data.txt', delimiter=',')
filedata=filedata.astype('int32')
print(filedata)

[[ 13  14  17  18  19]
 [  4   5   8   3  20]
 [ 34  50 100  60  70]]


# **Boolean Masking and Advanced indexing**

In [108]:
#Find data greater than a specific number
filedata>50 #T/F
filedata[filedata>50] #Gets the numbers
np.any(filedata>50, axis=0)
np.all(filedata>50, axis=0)

array([False, False, False, False, False])

In [163]:
#Find data greater than a specific range
((filedata>50) & (filedata<100))

~((filedata>50) & (filedata<100))

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False, False]])

In [160]:
#Index with a list
f=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
f[[1, 2, 8]]

array([2, 3, 9])