<a href="https://colab.research.google.com/github/Tahsin-20/Python-Libraries/blob/main/Numpy/Numpy-03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [ ]:
#Sorts an array
a = np.random.randint(1,100,15)
a

array([83, 16, 78, 31, 60,  2, 56, 18, 87,  8, 41, 52, 66, 44, 47])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[17, 23, 42, 72],
       [ 4, 74, 16, 70],
       [27, 63, 18, 13],
       [42,  2, 36,  9],
       [79, 79, 96,  7],
       [13, 40, 45, 75]])

In [ ]:
np.sort(a)[::-1]

array([87, 83, 78, 66, 60, 56, 52, 47, 44, 41, 31, 18, 16,  8,  2])

In [ ]:
np.sort(b,axis=0)

array([[ 4,  2, 16,  7],
       [13, 23, 18,  9],
       [17, 40, 36, 13],
       [27, 63, 42, 70],
       [42, 74, 45, 72],
       [79, 79, 96, 75]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [ ]:
#Appends any number of array
np.append(a,200)

array([ 83,  16,  78,  31,  60,   2,  56,  18,  87,   8,  41,  52,  66,
        44,  47, 200])

In [ ]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[17.        , 23.        , 42.        , 72.        ,  0.49344484],
       [ 4.        , 74.        , 16.        , 70.        ,  0.49500687],
       [27.        , 63.        , 18.        , 13.        ,  0.22587751],
       [42.        ,  2.        , 36.        ,  9.        ,  0.41602932],
       [79.        , 79.        , 96.        ,  7.        ,  0.64060935],
       [13.        , 40.        , 45.        , 75.        ,  0.49840221]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
#Concatenates multiple arrays (Can be used as a replacement of Vertical & Horizontal Stacking)
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

np.concatenate((c,d),axis=0)
np.concatenate((c,d),axis=1)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [ ]:
#Finds out the unique elements
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [ ]:
#Expands dimension
np.expand_dims(e,axis=0)
np.expand_dims(e,axis=1)

array([[1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
# Find all indices with value greater than 50
np.where(a>50)

(array([ 0,  2,  4,  6,  8, 11, 12]),)

In [ ]:
# Replace all values > 50 with 0 (Condition, Value if true, Value if False)
np.where(a>50,0,a)

array([ 0, 16,  0, 31,  0,  2,  0, 18,  0,  8, 41,  0,  0, 44, 47])

### np.argmax & np.argmin

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [ ]:
#Finds the index of largest number in the array
np.argmax(a)

np.int64(8)

In [ ]:
np.argmax(b,axis=0) #Columnwise
np.argmax(b,axis=1) #Row-wise

array([3, 1, 1, 0, 2, 3])

In [ ]:
# Finds the index of smallest number in the array
np.argmin(a)

np.int64(5)

### np.cumsum & np.cumprod

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [ ]:
#Finds out the cummulative sum
np.cumsum(a)

array([ 83,  99, 177, 208, 268, 270, 326, 344, 431, 439, 480, 532, 598,
       642, 689])

In [ ]:
np.cumsum(b,axis=0)
np.cumsum(b,axis=1)

array([[ 17,  40,  82, 154],
       [  4,  78,  94, 164],
       [ 27,  90, 108, 121],
       [ 42,  44,  80,  89],
       [ 79, 158, 254, 261],
       [ 13,  53,  98, 173]])

In [ ]:
#Finds out cummulative product
np.cumprod(a)

array([                  11,                  583,                16324,
                     816200,             31015600,           1147577200,
               107872256800,        9924247625600,       49621238128000,
           1488637143840000,   101227325781120000,   911045932030080000,
       -2725393596491966464, -5450787192983932928, -3786066610405281792])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [ ]:
#Finds out nth percentile
np.percentile(a,50)

37.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
#Plots histograms
np.histogram(a,bins=[0,10,20,30,40,50])

(array([2, 2, 0, 1, 3]), array([ 0, 10, 20, 30, 40, 50]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
#Finds out correlation between multiple objects
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [ ]:
#Searches for a number of specific items in our targetted array
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([60])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [ ]:
#Reverses the order of array
np.flip(a)

array([21,  2, 78,  9, 68, 30,  5, 92, 94, 37, 38, 50, 28, 53, 11])

In [ ]:
np.flip(b,axis=0)
np.flip(b,axis=1)

array([[72, 42, 23, 17],
       [70, 16, 74,  4],
       [13, 18, 63, 27],
       [ 9, 36,  2, 42],
       [ 7, 96, 79, 79],
       [75, 45, 40, 13]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [ ]:
#Replaces specific elements of array with given values
np.put(a,[0,1],[110,530])
a

array([110, 530,  78,  31,  60,   2,  56,  18,  87,   8,  41,  52,  66,
        44,  47])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [ ]:
#Removes specific indexed values from the array
np.delete(a,[0,2,4])

array([530,  31,   2,  56,  18,  87,   8,  41,  52,  66,  44,  47])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d

In [ ]:
#Finds union of multiple arrays
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#Finds intersection of multiple arrays
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
#Finds elements (n,m) which are in n but not in m
np.setdiff1d(n,m)

array([6, 7])

In [ ]:
#Gets all the elements except the common (X-OR)
np.setxor1d(m,n)

array([1, 2, 6, 7])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
#Clipping values in a certain range
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 31, 60, 25, 56, 25, 75, 25, 41, 52, 66, 44, 47])