<a href="https://colab.research.google.com/github/Tahsin-20/Python-Libraries/blob/main/Numpy/Numpy-01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# **Basic operations**



In [ ]:
a=np.array([1, 2, 3])
print(a)

[1 2 3]


In [ ]:
b=np.array([[2.0, 3.0, 5.9],[4.9, 6.7, 3.4]])
print(b)

[[2.  3.  5.9]
 [4.9 6.7 3.4]]


In [ ]:
#Get dimension
a.ndim
b.ndim

2

In [ ]:
#Get shape
a.shape
b.shape

(2, 3)

In [ ]:
#Get data type
a.dtype
b.dtype

dtype('float64')

In [ ]:
#Get size
a.itemsize
b.itemsize

8

In [ ]:
#Get total size
a.nbytes
b.nbytes

48

# **Accessing/Changing Specific elements, rows, columns etc**

In [ ]:
a=np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])

In [ ]:
#Get a specific element [r, c]
a[1,0]
a[1, -7]

np.int64(8)

In [ ]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#Get a specific column
a[:, 3]

array([ 4, 11])

In [ ]:
#Fancy way [row/col.no, start_index : stop_index : step_size]
a[0, 1:6:2]

array([2, 4, 6])

In [ ]:
#Changing elements
a[1,3]=20
#Changing series of elements
a[:,3]=30
print(a)

[[ 1  2  3 30  5  6  7]
 [ 8  9 10 30 12 13 14]]


In [ ]:
#Iterating each element
for i in np.nditer(a):
  print(i)

1
2
3
30
5
6
7
8
9
10
30
12
13
14


**3D Example**

In [ ]:
b=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Get specific element (work outside in)
b[0,1,1]
b[0, :, 1]

array([2, 4])

In [ ]:
#Replace
b[: , 1, :]=[[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# **Initializing different types of array**

In [ ]:
#Equal spaced array in the digit (start, stop, number of terms)
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
#Initializes an array with numbers of specific range
np.arange(1, 10)
np.arange(1, 10, 2) #Step size

array([1, 3, 5, 7, 9])

In [ ]:
#All 0s matrix
np.zeros(5)
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#All 1s matrix
np.ones(4)
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#All any number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [ ]:
#All any number in an already created array (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
#Random decimal numbers
np.random.rand(5,6)

array([[0.05585077, 0.66830014, 0.39319523, 0.73216633, 0.45003014,
        0.84062356],
       [0.24018073, 0.1027543 , 0.40764541, 0.18164387, 0.265617  ,
        0.67533842],
       [0.15794655, 0.04598817, 0.673822  , 0.06626627, 0.19751891,
        0.90366535],
       [0.36230664, 0.30248481, 0.59644481, 0.56127509, 0.57538651,
        0.63457578],
       [0.55457355, 0.09436738, 0.51873933, 0.39527129, 0.27215848,
        0.10063737]])

In [ ]:
#Random integer number (from, to[exclusive], size=(r, c))
np.random.randint(2,6, size=(3,3))

array([[4, 5, 5],
       [4, 4, 3],
       [2, 5, 3]])

In [ ]:
#Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#Repeat an array
arr=np.array([[1, 2, 3]])
r1=np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
#Copying arrays
d=np.array([1, 2, 3])
c=d.copy()
c[0]=100
print(c)
print(d)

[100   2   3]
[1 2 3]


# **Mathematical Operations**

In [ ]:
#Addition
a=np.array([1, 2, 3, 4])
a+2

array([3, 4, 5, 6])

In [ ]:
#Subtraction
a=np.array([1, 2, 3, 4])
a-2

array([-1,  0,  1,  2])

In [ ]:
#Multiplication
a=np.array([1, 2, 3, 4])
a*2

array([2, 4, 6, 8])

In [ ]:
#Division
a=np.array([1, 2, 3, 4])
a/2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
#Power
a=np.array([1, 2, 3, 4])
a**2

array([ 1,  4,  9, 16])

In [ ]:
#Take sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
#Take cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
#Logarithm
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [ ]:
#Exponent
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [ ]:
#Round/Floor/Ceil
np.round([1.2, 1.5, 1.6])
np.floor([1.2, 1.5, 1.6])
np.ceil([1.2, 1.5, 1.6])

array([2., 2., 2.])

In [ ]:
#You can do all the things between two numpy arrays too
a=np.array([1, 2, 3, 4])
b=np.array([1, 0, 1, 0])
a+b
a-b
a*b
a/b #smth / 0 is infinity

/tmp/ipykernel_2715/3311733407.py:7: RuntimeWarning: divide by zero encountered in divide
  a/b #smth / 0 is infinity


array([ 1., inf,  3., inf])

# **Linear Algebra**

In [ ]:
#Dot product
a1=np.arange(1,13).reshape(3,4)
a2=np.arange(1,13).reshape(4,3)
np.dot(a1, a2)

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330]])

In [ ]:
#Multiplication of two matrices
e=np.ones((2,3))
print(e)
f=np.full((3,2),2)
print(f)

np.matmul(e,f)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
A = np.array([[4, 11, 14],
              [8, 7, -2],
              [1, 5, 3]])

In [ ]:
#Find the determinant
np.linalg.det(A)

np.float64(299.99999999999994)

In [ ]:
#Trace of matrix
np.trace(A)

np.int64(14)

In [ ]:
#Singular vector decomposition
np.linalg.svd(A)

SVDResult(U=array([[-0.90749124,  0.32823268, -0.26215065],
       [-0.3056737 , -0.9440455 , -0.12386152],
       [-0.28813755, -0.03227069,  0.95704512]]), S=array([19.80787839,  9.49221315,  1.59556982]), Vh=array([[-0.32126066, -0.68471782, -0.65418124],
       [-0.66072094, -0.33281095,  0.67281848],
       [-0.67840948,  0.64838136, -0.34548833]]))

In [ ]:
#Eigenvalues & Eigenvectors
np.linalg.eig(A)

EigResult(eigenvalues=array([16.88759423+0.j        , -1.44379712+3.95979413j,
       -1.44379712-3.95979413j]), eigenvectors=array([[ 0.77541218+0.j        ,  0.71673995+0.j        ,
         0.71673995-0.j        ],
       [ 0.57426679+0.j        , -0.55709462-0.17977938j,
        -0.55709462+0.17977938j],
       [ 0.2625902 +0.j        ,  0.15901814+0.3439797j ,
         0.15901814-0.3439797j ]]))

In [ ]:
#Matrix norms
np.linalg.norm(A) #Standard Frobenius norm
np.linalg.norm(A, ord=2) #Spectral norm (L2 norm)

np.float64(19.807878393893564)

In [ ]:
#Inverse of matrix
np.linalg.inv(A)

array([[ 0.10333333,  0.12333333, -0.4       ],
       [-0.08666667, -0.00666667,  0.4       ],
       [ 0.11      , -0.03      , -0.2       ]])

# **Statistics**

In [ ]:
stats=np.array([[1, 2, 3], [4, 5, 6]])
# 0->column , 1->row

In [ ]:
#Minimum number
np.min(stats)
np.min(stats, axis=0)
np.min(stats, axis=1)

array([1, 4])

In [ ]:
#Maximum number
np.max(stats)
np.max(stats, axis=0)
np.max(stats, axis=1)

array([3, 6])

In [ ]:
#Mean/Average
np.mean(stats)
np.mean(stats, axis=0)
np.mean(stats, axis=1)

array([2., 5.])

In [ ]:
#Median
np.median(stats)
np.median(stats, axis=0)
np.median(stats, axis=1)

array([2., 5.])

In [ ]:
#Standard Deviation
np.std(stats)
np.std(stats, axis=0)
np.std(stats, axis=1)

array([0.81649658, 0.81649658])

In [ ]:
#Variance
np.var(stats)
np.var(stats, axis=0)
np.var(stats, axis=1)

array([0.66666667, 0.66666667])

In [ ]:
#Summation
np.sum(stats)
np.sum(stats, axis=0)
np.sum(stats, axis=1)

array([ 6, 15])

# **Reorganizing arrays**

In [ ]:
#Reshaping matrices (Be careful with invalid reshaping)
before=np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after=before.reshape((8,1))
after=before.reshape((4,2))
after=before.reshape((2,2,2))
after=before.reshape((2,4))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#Ravel (Shifts array of any dimension to 1D array)
before.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#Transpose matrix
np.transpose(before)
before.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
#Changing datatype
before.astype('int32')

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)

In [ ]:
#Vertically stacking vectors
v1=np.array([1, 2, 3, 4])
v2=np.array([5, 6, 7, 8])

v3=np.vstack([v1, v2])
np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
#Vertically split (array, no. of splits)
np.vsplit(v3, 2) #Always split in equal divisions

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [ ]:
#Horizontal stacking vectors
h1=np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
h2=np.array([[9, 10, 11, 12], [13, 14, 15, 16]])

h3=np.hstack((h1, h2))
print(h3)

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


In [ ]:
#Horizontal splitting (array, no. of splits)
np.hsplit(h3, 4) #Always split in equal divisions

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]]),
 array([[ 9, 10],
        [13, 14]]),
 array([[11, 12],
        [15, 16]])]

# **Miscellaneous**

In [ ]:
%%writefile data.txt
13, 14, 17, 18, 19
4, 5, 8, 3, 20
34, 50, 100, 60, 70

Overwriting data.txt


In [ ]:
#Load data from a file
filedata=np.genfromtxt('data.txt', delimiter=',')
filedata=filedata.astype('int32')
print(filedata)

[[ 13  14  17  18  19]
 [  4   5   8   3  20]
 [ 34  50 100  60  70]]


# **Boolean Masking and Advanced indexing**

In [ ]:
#Find data greater than a specific number (Boolean Indexing)
filedata>50 #T/F
filedata[filedata>50] #Gets the requried numbers
np.any(filedata>50, axis=0)
np.all(filedata>50, axis=0)

array([False, False, False, False, False])

In [ ]:
#Find data greater than a specific range
((filedata>50) & (filedata<100))

~((filedata>50) & (filedata<100))  # '~' sign means NOT

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False, False]])

In [ ]:
#More logical operations
filedata[filedata%2==0] #Finds out even numbers
filedata[(filedata%2==0) & (filedata>50)] #Use '&' sign instead of and

array([100,  60,  70], dtype=int32)

In [ ]:
#Index with a list (Fancy indexing)
f=np.array([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12],
            [13, 14, 15, 16]])
f[[0,3]]
f[:,[1,3]]

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])